export type CuratedTitle = { title: string; year?: string };

// 54 judul lintas negara & genre, dibagi 3 batch @18 supaya tiap klik
// tetap di bawah batas waktu function Vercel (Hobby: 10 detik).
export const CURATED_BATCHES: CuratedTitle[][] = [
  [
    { title: "Citizen Kane" },
    { title: "Casablanca" },
    { title: "Psycho" },
    { title: "Singin' in the Rain" },
    { title: "Seven Samurai" },
    { title: "Spirited Away" },
    { title: "Akira" },
    { title: "Bicycle Thieves" },
    { title: "Life Is Beautiful" },
    { title: "Cinema Paradiso" },
    { title: "Amelie" },
    { title: "The 400 Blows" },
    { title: "Pather Panchali" },
    { title: "Sholay" },
    { title: "Oldboy" },
    { title: "Parasite" },
    { title: "The Third Man" },
    { title: "Pengabdi Setan" },
  ],
  [
    { title: "Gone with the Wind" },
    { title: "The Wizard of Oz" },
    { title: "12 Angry Men" },
    { title: "Some Like It Hot" },
    { title: "Rear Window" },
    { title: "Sunset Boulevard" },
    { title: "Vertigo" },
    { title: "Taxi Driver" },
    { title: "Jaws" },
    { title: "Lawrence of Arabia" },
    { title: "The Bridge on the River Kwai" },
    { title: "A Clockwork Orange" },
    { title: "La Haine" },
    { title: "Leon: The Professional" },
    { title: "The Good, the Bad and the Ugly" },
    { title: "Metropolis" },
    { title: "Das Boot" },
    { title: "Run Lola Run" },
  ],
  [
    { title: "Rashomon" },
    { title: "Ran" },
    { title: "My Neighbor Totoro" },
    { title: "Memories of Murder" },
    { title: "The Handmaiden" },
    { title: "Mother India" },
    { title: "Lagaan" },
    { title: "Farewell My Concubine" },
    { title: "Hero", year: "2002" },
    { title: "In the Mood for Love" },
    { title: "The Seventh Seal" },
    { title: "Pan's Labyrinth" },
    { title: "Amores Perros" },
    { title: "Roma", year: "2018" },
    { title: "City of God" },
    { title: "A Separation" },
    { title: "Battleship Potemkin" },
    { title: "The Raid: Redemption" },
  ],
];
